management:
  endpoints:
    web:
      exposure:
        include: '*' # 声明允许所有的endpoint


# 用来测试nacos config配置的属性
user:
  name1: test # 这里取变量名为name1，因为springboot会加载系统环境变量，username和user.name取到的都是系统变量下的用户名，而不是这里配置的
  age: 18